package com.quizapp.modes.llmmode.llm;

import java.util.*;

import com.quizapp.modes.llmmode.api.*;
import com.quizapp.modes.llmmode.helpers.*;
import com.quizapp.ui.*;

public class LLM {
    public static void StartLLMQuiz(Scanner sc) {
        MenuUI.printModeDescription("AI LLM Mode" ,
            "Dynamic questions generated by AI" ,
            "Enter any topic to get custom questions\nPowered by Gemma Local or Gemini Cloud");

        MenuUI.pressEnterToContinue(sc);

        try {
            Screen.clear();

            Terminal.print(Theme.BORDER_COLOR + "╭────────────────────────────────────╮" + Theme.RESET);
            Terminal.print(Theme.BORDER_COLOR + "│" + Theme.TITLE_TEXT + Terminal.centerLine("SELECT AI ENGINE" , 36) + Theme.BORDER_COLOR + "│" + Theme.RESET);
            Terminal.print(Theme.BORDER_COLOR + "├────────────────────────────────────┤" + Theme.RESET);
            Terminal.print(Theme.BORDER_COLOR + "│" + Theme.OPTION_TEXT + Terminal.padRight("  [1] Local Model Gemma" , 36) + Theme.BORDER_COLOR + "│" + Theme.RESET);
            Terminal.print(Theme.BORDER_COLOR + "│" + Theme.OPTION_TEXT + Terminal.padRight("  [2] Cloud Model Gemini" , 36) + Theme.BORDER_COLOR + "│" + Theme.RESET);
            Terminal.print(Theme.BORDER_COLOR + "╰────────────────────────────────────╯" + Theme.RESET);

            Terminal.printEmptyLines(1);
            Terminal.printInline(Theme.QUESTION_TEXT + "> Choice: " + Theme.RESET);

            int modelChoice = sc.nextInt();
            sc.nextLine();

            Screen.clear();

            Terminal.printInline(Theme.QUESTION_TEXT + "> Enter topic: " + Theme.RESET);
            String topic = sc.nextLine();

            Terminal.printInline(Theme.QUESTION_TEXT + "> Difficulty: " + Theme.RESET);
            String difficulty = sc.nextLine();

            Terminal.printEmptyLines(1);
            Animator.loading("Generating AI Questions" , 6 , 250);

            Set<String> questions = new LinkedHashSet<>();

            int attempts = 0;
            int maxAttempts = 3;

            while (questions.size() < 10 && attempts < maxAttempts) {
                String rawResponse = "";

                if (modelChoice == 1) {
                    rawResponse = GemmaClient.generateQuiz(topic , difficulty);
                } else if (modelChoice == 2) {
                    rawResponse = GeminiClient.generateQuiz(topic , difficulty);
                } else {
                    Terminal.print(Theme.FEEDBACK_WRONG + "Wrong Choice" + Theme.RESET);
                    return;
                }

                List<String> parsed = QuizParser.extractValidQuestions(rawResponse);

                for (String q : parsed) {
                    if (questions.size() == 10) break;

                    questions.add(q);
                }

                attempts++;
            }

            List<String> finalQuestions = new ArrayList<>(questions);

            Collections.shuffle(finalQuestions);

            FileWriterUtil.writeQuestions(finalQuestions);

            Terminal.print(Theme.FEEDBACK_CORRECT + "Generated " + questions.size() + " questions" + Theme.RESET);

            Screen.pause(1500);

            StartQuiz.Start(sc);
        } catch (Exception e) {
            System.err.println("Critical Error in LLM Mode: " + e.getMessage());
            e.printStackTrace();
        }
    }
}