package com.quizapp.modes.llmmode.llm;

import java.util.*;

import com.quizapp.modes.llmmode.api.*;
import com.quizapp.modes.llmmode.helpers.*;
import com.quizapp.ui.*;

public class LLM {
    public static void StartLLMQuiz(Scanner sc) {
        MenuUI.printModeDescription("AI LLM Mode" ,
            "Dynamic questions generated by AI" ,
            "Enter any topic to get custom questions\nPowered by Gemma (Local) or Gemini (Cloud)");

        MenuUI.pressEnterToContinue(sc);

        try {
            Screen.clear();

            System.out.println(Theme.BORDER_COLOR + "╔════════════════════════════════════╗" + Theme.RESET);
            System.out.println(Theme.BORDER_COLOR + "║" + Theme.TITLE_TEXT + "          SELECT AI ENGINE          " + Theme.BORDER_COLOR + "║" + Theme.RESET);
            System.out.println(Theme.BORDER_COLOR + "╠════════════════════════════════════╣" + Theme.RESET);
            System.out.println(Theme.BORDER_COLOR + "║" + Theme.OPTION_TEXT + "  [1] Local Model (Gemma)           " + Theme.BORDER_COLOR + "║" + Theme.RESET);
            System.out.println(Theme.BORDER_COLOR + "║" + Theme.OPTION_TEXT + "  [2] Cloud Model (Gemini)          " + Theme.BORDER_COLOR + "║" + Theme.RESET);
            System.out.println(Theme.BORDER_COLOR + "╚════════════════════════════════════╝" + Theme.RESET);
            System.out.print(Theme.QUESTION_TEXT + "> Choice: " + Theme.RESET);

            int modelChoice = sc.nextInt();
            sc.nextLine();

            Screen.clear();

            System.out.print(Theme.QUESTION_TEXT + "> Enter topic: " + Theme.RESET);
            String topic = sc.nextLine();

            System.out.print(Theme.QUESTION_TEXT + "> What difficulty do you want?: " + Theme.RESET);
            String difficulty = sc.nextLine();

            System.out.println("\n" + Theme.TIMER_TEXT + "Generating Questions..." + Theme.RESET);

            Set<String> questions = new LinkedHashSet<>();

            int attempts = 0;
            int maxAttempts = 3;

            while (questions.size() < 10 && attempts < maxAttempts) {
                String rawResponse = "";

                if (modelChoice == 1) {
                    rawResponse = GemmaClient.generateQuiz(topic , difficulty);
                } else if (modelChoice == 2) {
                    rawResponse = GeminiClient.generateQuiz(topic , difficulty);
                } else {
                    System.out.println(Theme.FEEDBACK_WRONG + "Wrong Choice" + Theme.RESET);
                    return;
                }

                List<String> parsed = QuizParser.extractValidQuestions(rawResponse);

                for (String q : parsed) {
                    if (questions.size() == 10) break;

                    questions.add(q);
                }

                attempts++;
            }

            List<String> finalQuestions = new ArrayList<>(questions);

            Collections.shuffle(finalQuestions);

            FileWriterUtil.writeQuestions(finalQuestions);

            System.out.println();
            Animator.loading("Generating AI Questions", 2500);
            Screen.pause(1500);

            StartQuiz.Start(sc);
        } catch (Exception e) {
            System.err.println("Critical Error in LLM Mode: " + e.getMessage());
            e.printStackTrace();
        }
    }
}